name: build

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
  pull_request:
  repository_dispatch:
    types: [brave-version-updated]

jobs:
  build:
    uses: portapps/.github/.github/workflows/app-build.yml@master
